### ISSUE TITLE
Allvarliga felmeddelanden

### ISSUE THREAD

**Issue by jonkpirateboy** [SwedbankPay/swedbank-pay-woocommerce-checkout#143]
Om vi inaktiverar Swedbank Pay Payments så får vi följande felmeddelande och hela sajten ligger nere:

`Fatal error: Uncaught Error: Class 'SwedbankPay\Core\Adapter\WC_Adapter' not found in [path]/wp-content/plugins/swedbank-pay-woocommerce-checkout/includes/class-wc-gateway-swedbank-pay-checkout.php:289 Stack trace: #0 [path]/wp-content/plugins/swedbank-pay-woocommerce-checkout/includes/class-wc-swedbank-plugin.php(177): WC_Gateway_Swedbank_Pay_Checkout->__construct() #1 [path]/wp-content/plugins/swedbank-pay-woocommerce-checkout/swedbank-pay-woocommerce-checkout.php(64): SwedbankPay\Checkout\WooCommerce\WC_Swedbank_Plugin::register_gateway('WC_Gateway_Swed...') #2 [path]/wp-includes/class-wp-hook.php(308): WC_Swedbank_Pay_Checkout->woocommerce_loaded('') #3 [path]/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array) #4 [path]/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #5 [path]/wp-content/plugins/woocommer in [path]/wp-content/plugins/swedbank-pay-woocommerce-checkout/includes/class-wc-gateway-swedbank-pay-checkout.php on line 289`

Detta även om den har legat som deaktiverad under [domain]/wp-admin/admin.php?page=wc-settings&tab=checkout&section=payex_psp_cc

Och om vi har den Aktiv under plugins och deaktiverad enligt ovan så får vi felmeddelandet (under rubriken "Swedbank Pay Payments Actions") på vissa ordrar:

`Fatal error: Uncaught Error: Call to a member function get_image_id() on bool in [path]/wp-content/plugins/swedbank-pay-payments/vendor/swedbank-pay/swedbank-pay-woocommerce-core/src/SwedbankPay/Core/Adapter/WC_Adapter.php:271 Stack trace: #0 [path]/wp-content/plugins/swedbank-pay-payments/vendor/swedbank-pay/swedbank-pay-woocommerce-core/src/SwedbankPay/Core/Core.php(146): SwedbankPay\Core\Adapter\WC_Adapter->getOrderData(15913) #1 [path]/wp-content/plugins/swedbank-pay-payments/vendor/swedbank-pay/swedbank-pay-woocommerce-core/src/SwedbankPay/Core/Library/OrderAction.php(39): SwedbankPay\Core\Core->getOrder(15913) #2 [path]/wp-content/plugins/swedbank-pay-payments/templates/admin/payment-actions.php(34): SwedbankPay\Core\Core->canCapture(15913) #3 [path]/wp-content/plugins/woocommerce/includes/wc-core-functions.php(345): include('/home/therocks/...') #4 [path]/wp-content/plugins/swedbank-pay-payments/i in [path]/wp-content/plugins/swedbank-pay-payments/vendor/swedbank-pay/swedbank-pay-woocommerce-core/src/SwedbankPay/Core/Adapter/WC_Adapter.php on line 271`

**Comment by aait** [comment]
Looks like you've downloaded plugin from git repository
But forgot to run composer install
Maybe try to reinstall either through repository or via Wordpress Plugin Directory
/R

**Comment by jonkpirateboy** [comment]
So if i install from [here](https://wordpress.org/plugins/swedbank-pay-checkout/), I don't have to run composer install?

**Comment by aait** [comment]
Correct /R
